### ISSUE TITLE
On Linux, i cant access my sound card while the mod app is using itt.  

### ISSUE THREAD

**Issue by billyblackburn** [moddevices/mod-desktop#39]
so the app itself works great and has better latency than ardour, but im unable to use any DAW or anything with the app running.  this is actually kind of a feature since it keeps my doing only once thing at a time, but I want to integrate the mod desktop app with renoise...like if I use BYOD, I can use qjackctl to port the BYOD output to renoise input and i can program some accompaniment with my phrases.    hoesntly, ive never seen an app hijack my soundcard like that before........im not complaining, but i just want to discuss this with other linux users........my distro is popOS and im long time user ive been following falktx since when I first started over 10 years ago.,...back then it was just rakarrak until guitarix came out :)

**Comment by falkTX** [comment]
Just went to check with the latest builds, the option is for sure in there.

![image](https://github.com/moddevices/mod-desktop-app/assets/1334853/755f5893-38e5-4a9b-a746-24a46312d8ac)

So this is more of a documentation issue rather than feature-issue, the feature is already there.

**Comment by billyblackburn** [comment]
Yes it is listed in my version as well, but it never connects to the server.   I have to select my soundcard and then it starts a jack server.  I'm not sure why it doesn't work with pipe wire, I'll try to check the logs

**Comment by billyblackburn** [comment]
![Screenshot from 2024-02-01 23-47-37](https://github.com/moddevices/mod-desktop/assets/7400122/8d789323-f046-449b-b6c8-5c1435bfa1fe)

**Comment by falkTX** [comment]
should be working well now with 0.0.7, including jack midi support too.
please try and let me know how it works for you. if building from source please delete the whole ~/PawPawBuilds folder

**Comment by billyblackburn** [comment]
Nice, I'll have to try it...., but let me ask a question for you...on the mod app I can get down to 128 samples@ the 48k, but on ardour I can only get jack to 256......is there something y'all are tweaking to allow the lower quantum...2.7ms is so nice I'm gonna try the new build now :)

**Comment by billyblackburn** [comment]
To add, I got the pipe wire/jack option to work with the new build, but I am unable to get down to 128 buffer size unless I choose my soundcard directly then it creates a 'Dummy' device.   
How is it that the mod app can achieve lower latency at 128 vs 256, but anything else I try will not work at 128?   I would like to find out why it works so I can enable it system wide.  I'm on popOS btw

**Comment by billyblackburn** [comment]
ok, so its all working great now...i went to pulse audio config and changed my scarlett to 'Pro Audio' intsead on the default.  i run mod desktop in jack/pipewire mode and heres the command it shows...  Starting jackd using:
-R -S -n mod-desktop -C ./jack/jack-session-alsamidi.conf -v -d portaudio -r 48000 -p 64 -d JACK::system.  i hope this was the setting that fixes it.  there is 'direct scarlett' and 'Pro Audio' as a profile. imm gonna leave it on tonight to see for x runs.  if this keeps worknig I will be elated.  thanmk you so much for all your work.  and for intriducing me to renoise!

**Comment by billyblackburn** [comment]
29      0      0   0.0us   0.0us  0.00  0.00    0                  Dummy-Driver
S   30      0      0    ---     ---   ---   ---     0                  Freewheel-Driver
I   39      0      0   0.0us   0.0us  0.00  0.00    0                  Midi-Bridge
R  108     64  48000  60.0us   0.1us  0.05  0.00    1    S32LE 2 48000 alsa_input.usb-Focusrite_Scarlett_2i4_USB-00.2.pro-input-0
R   98      0      0   3.5us   1.1us  0.00  0.00    0    S32LE 4 48000  + alsa_output.usb-Focusrite_Scarlett_2i4_USB-00.2.pro-output-0
R   91     64      0   3.6us  50.7us  0.00  0.04    0                   + MOD Desktop
R   94      0      0   4.6us   0.1us  0.00  0.00    0                   + qjackctl

**Comment by billyblackburn** [comment]
https://unix.stackexchange.com/questions/675239/the-pro-audio-profile-in-pipewire-for-audio-devices-sound-cards

**Comment by falkTX** [comment]
I think ardour is just a bit heavier, so needs a bigger buffer size to run.
mod-desktop uses a custom jack2 build with mod-host which is very lean. that is the only explanation I can give

by the way, using 64 frames is not really recommended. 128 is more widely tested and provides low enough latency

**Comment by billyblackburn** [comment]
ok, that makes sense.
