### ISSUE TITLE
[Featue request] Buffer size in pipewire

### ISSUE THREAD

**Issue by magillos** [moddevices/mod-desktop#43]
Could mod-desktop follow pipewire's buffer size rather than rely on what is set in launcher? It would be useful when paired with DAW or other programs.

**Comment by falkTX** [comment]
that is a no, the MOD ecosystem was designed to be run at 128/48kHz by default, with an optional double latency mode of 256 frames. the 64 frames option is there by request and is an exception.
no other buffer size values are wanted at this point.
