### ISSUE TITLE
MOD Desktop 0.0.9 crashes on start on NixOS/Hyprland

### ISSUE THREAD

**Issue by abrushworkriot** [moddevices/mod-desktop#48]
Hello!

It's gonna be a very lacking bug report, but I can't start the app.
I don't know if it's Wayland, missing dependencies or whatever, but when I try to execute mod-desktop, my terminal just plain crashes without any error, message box or anything.

I don't really have any ideas on how to even provide more information on the problem. Maybe I'm doing something stupid, I don't know.
My machine is AMD Ryzen 5800H/Radeon RX 6600M runnning NixOS stable 23.11 with Wayland(Hyprland).

**Comment by falkTX** [comment]
You can try to start the latest linux debug build https://github.com/moddevices/mod-desktop/actions/runs/7854391203/artifacts/1235467278

run it through valgrind or gdb to try to find some info on this. let me know if you need help on that. likely I should write down how to debug these kinda crashes somewhere..
