### ISSUE TITLE
Ask to access microphone on macOS 

### ISSUE THREAD

**Issue by alf45tar** [moddevices/mod-desktop#55]
MOD Desktop does not ask to access microphone on macOS Ventura. MOD Desktop do not receive any input.
Only MIDI input works.

**Comment by falkTX** [comment]
This is due to the application not being signed, to be fixed next week.

**Comment by falkTX** [comment]
please try with the build from https://github.com/moddevices/mod-desktop/actions/runs/8245361496/artifacts/1317766604

this should now work in theory, as the application is signed.
we need to do some testing before tagging a new release

**Comment by falkTX** [comment]
there was yet another thing missing, I was able to reproduce the issue and fix.
0.0.12 release should work https://github.com/moddevices/mod-desktop/releases/tag/0.0.12

**Comment by alf45tar** [comment]
0.0.12 works like a charm.
Thanks
