### ISSUE TITLE
how to get the dark theme on the panel?  i know it use Qt and im on gnome/pop OS but theres a way to do it?

### ISSUE THREAD

**Issue by billyblackburn** [moddevices/mod-desktop#56]
any help is welcomne, thanks for the great software.  this is my go to app for using NAM now.....

**Comment by falkTX** [comment]
not sure, it is supposed to follow the theme of the desktop. so the dark theme on the readme screenshot just comes from kde side.
and anyhow, it is such a minor detail we do not consider it important. the panel thing should be open once and then forgot about later

**Comment by billyblackburn** [comment]
Ok, I agree with you, it's not important
