### ISSUE TITLE
interactive info menus

### ISSUE THREAD

**Issue by RustoMCSpit** [moddevices/mod-desktop#64]
![image](https://github.com/user-attachments/assets/c43aafab-0683-42bb-baa0-5a8f6d02b0d7)

i should be able to dial the knobs here instead of it just being an image

this is how bitwig handles this https://youtu.be/DWjYedds-RQ?si=LSYoXfGu0Yc6jf9W&t=11

**Comment by dromer** [comment]
Why? this is just a screenshot not an active plugin.

How would it being interactive (aka some mock instance of the plugin UI) be any helpful?
